FROM python:3.14-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock README.md pyrightconfig.json ./
COPY src ./src
COPY scripts ./scripts
COPY .env .env

RUN uv sync --no-dev

ENV PYTHONPATH=/app/src

CMD ["uv", "run", "python", "scripts/run_indexer.py"]
